name: Deploy Node.js backend to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install & Build
        run: |
          npm ci
          if npm pkg get scripts.build | grep -qv 'undefined'; then
            npm run build
          fi

      - name: Package app
        run: |
          rm -rf node_modules
          tar -czf app.tar.gz \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='*.log' \
            .

      # Upload app bundle to EC2
      - name: Upload to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 3.87.108.144
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "app.tar.gz"
          target: "~/deploy/"

      # Deploy on EC2 + reload with PM2
      - name: Deploy & Restart on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 3.87.108.144
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            APP_NAME="myapp"
            APP_DIR="/home/ec2-user/cloudvault-backend"
            BUNDLE="/home/ec2-user/deploy/app.tar.gz"
            RELEASE_DIR="$APP_DIR/release-$(date +%s)"

            mkdir -p "$APP_DIR/releases"
            rm -rf "$RELEASE_DIR"
            mkdir -p "$RELEASE_DIR"

            tar -xzf "$BUNDLE" -C "$RELEASE_DIR"

            cd "$RELEASE_DIR"
            npm ci --omit=dev

            ln -sfn "$RELEASE_DIR" "$APP_DIR/current"

            # Restart with PM2
            if pm2 describe "$APP_NAME" >/dev/null 2>&1; then
              pm2 reload "$APP_NAME" --update-env
            else
              pm2 start dynamo.js --name "$APP_NAME"
            fi

            # Ensure it survives reboot
            pm2 save
